# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

install! 'cocoapods', :deterministic_uuids => false,
:integrate_targets => false

target 'sesh' do
  rn_path = '../node_modules/react-native'

  # React pods
  pod 'yoga', path: "#{rn_path}/ReactCommon/yoga/yoga.podspec"
  pod 'React', path: rn_path, subspecs: [
    'Core',
    'CxxBridge',
    'DevSupport',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
  ]

  # React Native third party dependencies podspecs
  pod 'DoubleConversion', :podspec => "#{rn_path}/third-party-podspecs/DoubleConversion.podspec"
  pod 'glog', :podspec => "#{rn_path}/third-party-podspecs/glog.podspec"
  pod 'Folly', :podspec => "#{rn_path}/third-party-podspecs/Folly.podspec"

  # Firebase
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'Firebase/Storage'

  # Facebook
  pod 'FBSDKCoreKit'
  pod 'FBSDKShareKit'
  pod 'FBSDKLoginKit'
  pod 'FBSDKPlacesKit'

  # CodePush
  pod 'CodePush', :path => '../node_modules/react-native-code-push'

  # Lottie
  pod 'lottie-ios', :path => '../node_modules/lottie-ios'
  pod 'lottie-react-native', :path => '../node_modules/lottie-react-native'

  # maps
  pod 'react-native-maps', :path => '../node_modules/react-native-maps'

  # gradient
  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'

  # squircle
  pod 'react-native-super-ellipse-mask', :path => '../node_modules/react-native-super-ellipse-mask'

  # interactable
  pod 'Interactable', :path => '../node_modules/react-native-interactable'

  # RNFS
  pod 'RNFS', :path => '../node_modules/react-native-fs'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == "React"
      target.remove_from_project
    end
  end
end
