# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'sesh' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for sesh
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    # 'BatchedBridge', # Required For React Native 0.45.0+
    'Core',
    'DevSupport',
    'RCTNetwork',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTBlob',
    'RCTVibration',
    'RCTImage'
    # Add any other subspecs you want to use in your project
  ]

  # FIREBASE
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'Firebase/Storage'

  # pod 'Firebase/Messaging'

  # FACEBOOK
  pod 'FBSDKCoreKit'
  pod 'FBSDKShareKit'
  pod 'FBSDKLoginKit'

  # LOTTIE
  pod 'lottie-ios', :path => '../node_modules/lottie-ios'
  pod 'lottie-react-native', :path => '../node_modules/lottie-react-native'

  pod 'react-native-maps', :path => '../node_modules/react-native-maps'

  #pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'RNReactNativeHapticFeedback', :path => '../node_modules/react-native-haptic-feedback'

  pod 'RNFS', :path => '../node_modules/react-native-fs'

  end
